# Generated by Django 4.1.7 on 2023-03-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marca",
            name="nome",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
